version: '3'

services:
  aggregator:
        build: .
        container_name: kba
        environment:
            # Make sure that you sent your chosen local Neo4j password here!
            - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/password}
        ports:
            - "8080:8080"
        depends_on:
            - "blackboard"
        networks:
            - default
  blackboard:
        image: neo4j:3.3.4
        container_name: blackboard
        environment:
            - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/password}
            
            # This sets java's heap size to 1G. If you get java.lang.OutOfMemoryError
            # then you may need to increase this.
            - _JAVA_OPTIONS="-Xmx1g"
        ports:
            - "7474:7474"
            - "7473:7473"
            - "7687:7687"
        volumes:
            # NOTE: if docker-compose is run under 'sudo' then $HOME will be 'root'
            - $HOME/neo4j/data:/data
            - $HOME/neo4j/import:/import
            - $HOME/neo4j/logs:/logs
networks:
    default:
        driver: bridge